# The name of this site
# This text displays in the back-office and
# can be used in templates through the site.name global variable
name: SFWD CMS Templates

### Protect Site by Password
### https://doc.locomotivecms.com/v4.0/docs/protect-a-site-by-a-password
### Uses page: app/views/pages/lock-screen.liquid
# private_access: true #can also be set in Site settings interface
# password: "!Password1"

# An array of domain aliases for the site
# This option is for sites on multi-site engines
domains: []

# An array of locales (languages) the site is available in
# The locale listed first is the site's default locale
# Locales are specified using ISO language codes
# Possible locales include: en, de, fr, pl, pt-BR, it, nl, nb, es, ru, et, ja, zh-CN
locales: [en]

# The site's timezone
# This converts the server's time to the site's time zone in templates
# The TimeZone class from Rail's ActiveSupport is used to interpret the string
# Sample timezone strings: Tokyo, Beijing, Moscow, Cairo, Paris, Pacific Time (US & Canada)
timezone: "Pacific Time (US & Canada)"

### Custom routes - https://doc.locomotivecms.com/v4.0/docs/custom-routes
# routes:
#   - "news/:year/:month": "blog_posts_list"
#   - "actualites/:year/:month": "blog_posts_list"
#   - "products/:category/:product_id": "product_template"

# For SEO purposes, sites may wish to add a relevant string to the <title> tag
# And include <meta type="keywords"> and <meta type="description">
# For this purpose you can set values for these variables here
# They can be accessed in templates through the site.seo_title, site.meta_keywords, and site.meta_description variables
# These can and should be edited in the backend
# seo_title: "" ### defaults to site.name
# meta_keywords: ""
# meta_description: ""

### You can control the display of the "Properties" section in the back-office
# metafields_ui:
#   label: # use a hash for localized versions
#     en: Global Fields # default
#   icon: file-alt # FontAwesome icons without the leading "fa-" string.
#   hint: "Lorem ipsum..."

# Each site can have its own set of custom properties organized in namespaces.
# First, define namespaces and their fields in the config/metafields_schema.yml file.
# Finally, set default values below as described in the example.
# You can access them in your liquid templates and snippets:
#   {{ site.metafields.<namespace>.<field> }}

metafields:
  theme:
    text_font_family: 'Lato, Helvetica, Arial'
    title_font_family: ''
    text_color: '#444'
    title_text_color: ''
    background_color: '#fff'
    background_image: ''
    font_urls: 'https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic'
    css_overrides: ''
    custom_head_html: ''

  bootstrap_4:
    primary: '#007bff'
    secondary: '#6c757d'
    success: '#28a745'
    info: '#17a2b8'
    warning: '#ffc107'
    danger: '#dc3545'
    light: '#f8f9fa'
    dark: '#343a40'
    breakpoint_xs: '0'
    breakpoint_sm: '576px'
    breakpoint_md: '768px'
    breakpoint_lg: '992px'
    breakpoint_xl: '1200px'
    font_family_sans_serif: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
    font_family_monospace: 'SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace'
    blue: '#007bff'
    indigo: '#6610f2'
    purple: '#6f42c1'
    pink: '#e83e8c'
    red: '#dc3545'
    orange: '#fd7e14'
    yellow: '#ffc107'
    green: '#28a745'
    teal: '#20c997'
    cyan: '#17a2b8'
    white: '#fff'
    gray: '#6c757d'
    gray-dark: '#343a40'

  company:
    name: Solid Foundation Web Development
    address: 5361 246A ST
    city: Aldergrove
    postal_code: V2Z 1H6
    phone: 604-309-8713
    email: weston@westonganger.com
    #hours: 

  # email_settings:
  #   from:
  #   smtp_address:
  #   smtp_port:
  #   smtp_user:
  #   smtp_password:
  #   authentication_type: plain
  #   enable_starttls_auto: true
